// src/pages/game-over/ui/game-over-page.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { loadFinalResult, clearFinalResult, type FinalResult } from '@/entities/session'
import styles from './game-over.module.scss'

function formatTime(ms: number): string {
  const seconds = Math.floor(ms / 1000)
  const minutes = Math.floor(seconds / 60)
  const remainingSeconds = seconds % 60
  if (minutes > 0) {
    return `${minutes}m ${remainingSeconds}s`
  }
  return `${seconds}s`
}

export function GameOverPage() {
  const navigate = useNavigate()
  const [result] = useState<FinalResult | null>(() => loadFinalResult())

  const handlePlayAgain = () => {
    clearFinalResult()
    navigate('/')
  }

  if (!result) {
    navigate('/')
    return null
  }

  let message = ''
  if (result.accuracy >= 85) {
    message = "Amazing! You're a tongue twister master!"
  } else if (result.accuracy >= 70) {
    message = 'Great job! Keep practicing!'
  } else {
    message = 'Good effort! Try again!'
  }

  return (
    <div className={styles.page}>
      <div className={styles.container}>
        <h1 className={styles.title}>Game Over!</h1>

        <div className={styles.scoreCard}>
          <div className={styles.scoreLabel}>Accuracy</div>
          <div className={styles.scoreValue}>{result.accuracy}%</div>
        </div>

        <div className={styles.scoreCard}>
          <div className={styles.scoreLabel}>Time</div>
          <div className={styles.scoreValue}>{formatTime(result.elapsedTime)}</div>
        </div>

        <p className={styles.message}>{message}</p>

        <div className={styles.buttons}>
          <button className={styles.playAgainButton} onClick={handlePlayAgain}>
            Play Again
          </button>
        </div>
      </div>
    </div>
  )
}

// src/pages/game-over/ui/GameOverPage.svelte
<script lang="ts">
  import { push } from 'svelte-spa-router';
  import { loadFinalResult, clearFinalResult, type FinalResult } from '@/entities/session';
  import { onMount } from 'svelte';
  import styles from './game-over.module.scss';

  function formatTime(ms: number): string {
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    if (minutes > 0) {
      return `${minutes}m ${remainingSeconds}s`;
    }
    return `${seconds}s`;
  }

  let result = $state<FinalResult | null>(null);

  onMount(() => {
    result = loadFinalResult();
  });

  function handlePlayAgain() {
    clearFinalResult();
    push('/');
  }
</script>

{#if !result}
  <div class={styles.page}>
    <div class={styles.container}>
      <p>Loading...</p>
    </div>
  </div>
{:else}
  {@const message = result.accuracy >= 85 ? "Amazing! You're a tongue twister master!" : result.accuracy >= 70 ? 'Great job! Keep practicing!' : 'Good effort! Try again!'}
  <div class={styles.page}>
    <div class={styles.container}>
      <h1 class={styles.title}>Game Over!</h1>

      <div class={styles.scoreCard}>
        <div class={styles.scoreLabel}>Accuracy</div>
        <div class={styles.scoreValue}>{result.accuracy}%</div>
      </div>

      <div class={styles.scoreCard}>
        <div class={styles.scoreLabel}>Time</div>
        <div class={styles.scoreValue}>{formatTime(result.elapsedTime)}</div>
      </div>

      <p class={styles.message}>{message}</p>

      <div class={styles.buttons}>
        <button class={styles.playAgainButton} onclick={handlePlayAgain}>
          Play Again
        </button>
      </div>
    </div>
  </div>
{/if}
